version: '3'
services:
  springboot:
    container_name: spring-book-review
    image: wongelone/spring-book-review:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"